### ISSUE TITLE
default assertion failure messages have become unhelpful

### ISSUE THREAD

**Issue by slingamn** [progval/irctest#118]
I broke one of my ZNC tests in development and:

```
        self.sendLine("viewer", "PRIVMSG *playback :play * %d" % (early_time,))
        messages = extract_playback_privmsgs(self.getMessages("viewer"))
>       self.assertEqual(set(messages), set([dm] + echo_messages))
E       AssertionError: None

irctest/server_tests/znc_playback.py:95: AssertionError
```

It looks like there's no sane default for `msg` here?

https://github.com/progval/irctest/blob/5e4ae7c99965801cd91d974637ad344a47b5414f/irctest/cases.py#L226

**Comment by progval** [comment]
that's weird, pytest should always show the two operands

**Comment by progval** [comment]
bisect tells me it's a regression in 0177c369dd716dbbc398fb279930d9f4661eea7a, which is very unhelpful...
