### ISSUE TITLE
decrease minimum Python version requirement

### ISSUE THREAD

**Issue by slingamn** [ProgVal/irctest#18]
https://github.com/ProgVal/irctest/blob/4ded96fbbacc9b9085a8dbe58e6469dacbf49cbd/irctest/irc_utils/junkdrawer.py#L11-L15

This does not work with Python 3.6, and does work with 3.8 (I'm not sure about 3.7).

There may be other, similar issues.

**Comment by ProgVal** [comment]
I'm on python 3.7 myself and all tests pass
