### ISSUE TITLE
Not supporting ECDSA is seen as a failure in all cases

### ISSUE THREAD

**Issue by DanielOaks** [ProgVal/irctest#2]
Since IRC ECDSA SASL isn't a standard, I don't think it should be seen as a failure for clients to not support it in all cases.

I've got a (dodgy) attempt at a fix [here](https://github.com/DanielOaks/irctest/commit/50281250f7a5d8b5a5c9bf81f66d1a3567a0ea90), but maybe it would be nice to allow controllers to set a variable like:
```
self.supported_sasl_mechs = ['PLAIN']
```

And if that list exists and the given mechanism isn't in that list, just skip the testing of it?

**Comment by ProgVal** [comment]
I have been thinking about this, and the best idea I had so far is to use [`SkipTest`](https://docs.python.org/3/library/unittest.html#unittest.SkipTest).
But I would like to show report at the end (ultimately generating something similar to [http://ircv3.net/software/clients.html](http://ircv3.net/software/clients.html)]), which does not look possible using `SkipTest`.
